<?php

/**
 * Company: Yee Technologies Pvt. Ltd. < www.yeetechnologies.com >
 * Author : Praveen Shivhare < praveen.tuffgeekers@gmail.com >
 */
 
/**
 * This is the model base class for the table "{{timezones}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Timezones".
 *
 * Columns in table "{{timezones}}" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $timezone
 *
 */
abstract class BaseTimezones extends GxActiveRecord {


	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{timezones}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Timezones|Timezones', $n);
	}

	public static function representingColumn() {
		return 'timezone';
	}

	public function rules() {
		return array(
			array('timezone', 'required'),
			array('timezone', 'length', 'max'=>100),
			array('timezone', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'timezone' => Yii::t('app', 'Timezone'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('timezone', $this->timezone, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}