<?php

/**
 * Company: Yee Technologies Pvt. Ltd. < www.yeetechnologies.com >
 * Author : Praveen Shivhare < praveen.tuffgeekers@gmail.com >
 */
 
/**
 * This is the model base class for the table "{{recipient}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Recipient".
 *
 * Columns in table "{{recipient}}" available as properties of the model,
 * followed by relations of table "{{recipient}}" available as properties of the model.
 *
 * @property integer $id
 * @property integer $sender_id
 * @property integer $receiver_id
 * @property string $date_created
 * @property string $date_modified
 * @property integer $created_by
 * @property integer $updated_by
 *
 * @property User $sender
 * @property User $receiver
 */
abstract class BaseRecipient extends GxActiveRecord {


	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{recipient}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Recipient|Recipients', $n);
	}

	public static function representingColumn() {
		return 'date_created';
	}

	public function rules() {
		return array(
			array('sender_id', 'required'),
			array('sender_id, receiver_id, created_by, updated_by', 'numerical', 'integerOnly'=>true),
			array('date_created, date_modified', 'safe'),
			array('receiver_id, date_created, date_modified, created_by, updated_by', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, sender_id, receiver_id, date_created, date_modified, created_by, updated_by', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'sender' => array(self::BELONGS_TO, 'User', 'sender_id'),
			'receiver' => array(self::BELONGS_TO, 'User', 'receiver_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'sender_id' => null,
			'receiver_id' => null,
			'date_created' => Yii::t('app', 'Date Created'),
			'date_modified' => Yii::t('app', 'Date Modified'),
			'created_by' => Yii::t('app', 'Created By'),
			'updated_by' => Yii::t('app', 'Updated By'),
			'sender' => null,
			'receiver' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('sender_id', $this->sender_id);
		$criteria->compare('receiver_id', $this->receiver_id);
		$criteria->compare('date_created', $this->date_created, true);
		$criteria->compare('date_modified', $this->date_modified, true);
		$criteria->compare('created_by', $this->created_by);
		$criteria->compare('updated_by', $this->updated_by);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}