<?php

/**
 * Company: Yee Technologies Pvt. Ltd. < www.yeetechnologies.com >
 * Author : Praveen Shivhare < praveen.tuffgeekers@gmail.com >
 */
 
/**
 * This is the model base class for the table "{{fixed_charges}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "FixedCharges".
 *
 * Columns in table "{{fixed_charges}}" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $applies_to_user
 * @property string $formula
 * @property string $date_created
 * @property string $date_modified
 * @property integer $created_by
 * @property integer $updated_by
 *
 */
abstract class BaseFixedCharges extends GxActiveRecord {


	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{fixed_charges}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'FixedCharges|FixedCharges', $n);
	}

	public static function representingColumn() {
		return 'formula';
	}

	public function rules() {
		return array(
			array('applies_to_user, formula', 'required'),
			array('applies_to_user, created_by, updated_by', 'numerical', 'integerOnly'=>true),
			array('date_created, date_modified', 'safe'),
			array('date_created, date_modified, created_by, updated_by', 'default', 'setOnEmpty' => true, 'value' => null),
			array('applies_to_user, formula, date_created, date_modified, created_by, updated_by', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'applies_to_user' => Yii::t('app', 'Applies To User'),
			'formula' => Yii::t('app', 'Formula'),
			'date_created' => Yii::t('app', 'Date Created'),
			'date_modified' => Yii::t('app', 'Date Modified'),
			'created_by' => Yii::t('app', 'Created By'),
			'updated_by' => Yii::t('app', 'Updated By'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('applies_to_user', $this->applies_to_user);
		$criteria->compare('formula', $this->formula, true);
		$criteria->compare('date_created', $this->date_created, true);
		$criteria->compare('date_modified', $this->date_modified, true);
		$criteria->compare('created_by', $this->created_by);
		$criteria->compare('updated_by', $this->updated_by);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}