<?php

/**
 * Company: Yee Technologies Pvt. Ltd. < www.yeetechnologies.com >
 * Author : Praveen Shivhare < praveen.tuffgeekers@gmail.com >
 */
 
/**
 * This is the model base class for the table "{{user}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "User".
 *
 * Columns in table "{{user}}" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $full_name
 * @property string $email
 * @property string $mobile
 * @property string $password
 * @property string $first_name
 * @property string $last_name
 * @property string $status_msg
 * @property string $date_of_birth
 * @property integer $gender
 * @property string $contact_address
 * @property string $city
 * @property string $country
 * @property string $nationality
 * @property integer $zipcode
 * @property string $emirates_front
 * @property string $emirates_back
 * @property string $emirates_id
 * @property string $emirates_expiry
 * @property integer $tos
 * @property integer $news_letters
 * @property integer $role_id
 * @property integer $state_id
 * @property integer $type_id
 * @property string $last_visit_time
 * @property string $last_action_time
 * @property string $last_password_change
 * @property string $activation_key
 * @property integer $login_error_count
 * @property integer $create_user_id
 * @property string $create_time
 *
 */
abstract class BaseUser extends GxActiveRecord {

	public $password_2 = null;
	
	public static function getStatusOptions($id = null)
	{
		$list = array("Draft","Published","Archive");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}	
	
 	public static function getMonthOptions($id = null)
	{
		for($monthNum = 1; $monthNum <= 12; $monthNum++){
            $months[$monthNum] = date('F', mktime(0, 0, 0, $monthNum, 1));
        }
        return $months;
	}	 
	
	public function getDateOptions()
	{
		for($dayNum = 1; $dayNum <= 31; $dayNum++){
			$days[$dayNum] = $dayNum;
		}
	
		return  $days;
	}
	
	public function getYearsArray()
	{
		$thisYear = date('Y', time());
	
		for($yearNum = $thisYear; $yearNum >= 1920; $yearNum--){
			$years[$yearNum] = $yearNum;
		}
	
		//return array(0 => 'Year') + $years;
		return $years;
		
	}
	

	function getCountry()
	{
		$country = array('AFG'=>'Afghanistan','ALA'=>'Aland Islands','ALB'=>'Albania','DZA'=>'Algeria','ASM'=>'American Samoa','AND'=>'Andorra','AGO'=>'Angola','AIA'=>'Anguilla','ATA'=>'Antarctica','ATG'=>'Antigua and Barbuda','ARG'=>'Argentina','ARM'=>'Armenia','ABW'=>'Aruba','AUS'=>'Australia','AUT'=>'Austria','AZE'=>'Azerbaijan',
				'BHS'=>'Bahamas','BHR'=>'Bahrain','BGD'=>'Bangladesh','BRB'=>'Barbados','BLR'=>'Belarus','BEL'=>'Belgium','BLZ'=>'Belize','BEN'=>'Benin','BMU'=>'Bermuda','BTN'=>'Bhutan','BOL'=>'Bolivia, Plurinational State of','BES'=>'Bonaire, Sint Eustatius and Saba','BIH'=>'Bosnia and Herzegovina','BWA'=>'Botswana','BVT'=>'Bouvet Island','BRA'=>'Brazil',
				'IOT'=>'British Indian Ocean Territory','BRN'=>'Brunei Darussalam','BGR'=>'Bulgaria','BFA'=>'Burkina Faso',	'BDI'=>'Burundi','KHM'=>'Cambodia',	'CMR'=>'Cameroon','CAN'=>'Canada','CPV'=>'Cape Verde','CYM'=>'Cayman Islands','CAF'=>'Central African Republic','TCD'=>'Chad','CHL'=>'Chile','CHN'=>'China','CXR'=>'Christmas Island','CCK'=>'Cocos (Keeling) Islands',
				'COL'=>'Colombia','COM'=>'Comoros','COG'=>'Congo','COD'=>'Congo, the Democratic Republic of the','COK'=>'Cook Islands','CRI'=>'Costa Rica','CIV'=>"Cote d'Ivoire",'HRV'=>'Croatia','CUB'=>'Cuba','CUW'=>'Curacao','CYP'=>'Cyprus','CZE'=>'Czech Republic','DNK'=>'Denmark','DJI'=>'Djibouti','DMA'=>'Dominica','DOM'=>'Dominican Republic',
				'ECU'=>'Ecuador','EGY'=>'Egypt','SLV'=>'El Salvador','GNQ'=>'Equatorial Guinea','ERI'=>'Eritrea','EST'=>'Estonia','ETH'=>'Ethiopia','FLK'=>'Falkland Islands (Malvinas)','FRO'=>'Faroe Islands','FJI'=>'Fiji','FIN'=>'Finland','FRA'=>'France','GUF'=>'French Guiana','PYF'=>'French Polynesia','ATF'=>'French Southern Territories','GAB'=>'Gabon',
				'GMB'=>'Gambia','GEO'=>'Georgia','DEU'=>'Germany','GHA'=>'Ghana','GIB'=>'Gibraltar','GRC'=>'Greece','GRL'=>'Greenland','GRD'=>'Grenada','GLP'=>'Guadeloupe','GUM'=>'Guam','GTM'=>'Guatemala','GGY'=>'Guernsey','GIN'=>'Guinea','GNB'=>'Guinea-Bissau','GUY'=>'Guyana','HTI'=>'Haiti',
				'HMD'=>'Heard Island and McDonald Islands','VAT'=>'Holy See (Vatican City State)','HND'=>'Honduras','HKG'=>'Hong Kong','HUN'=>'Hungary','ISL'=>'Iceland','IND'=>'India','IDN'=>'Indonesia','IRN'=>'Iran, Islamic Republic of','IRQ'=>'Iraq','IRL'=>'Ireland','IMN'=>'Isle of Man','ISR'=>'Israel','ITA'=>'Italy',	'JAM'=>'Jamaica','JPN'=>'Japan',
				'JEY'=>'Jersey','JOR'=>'Jordan','KAZ'=>'Kazakhstan','KEN'=>'Kenya','KIR'=>'Kiribati','PRK'=>"Korea, Democratic People's Republic of",'KOR'=>'Korea, Republic of','KWT'=>'Kuwait','KGZ'=>'Kyrgyzstan','LAO'=>"Lao People's Democratic Republic",'LVA'=>'Latvia','LBN'=>'Lebanon','LSO'=>'Lesotho','LBR'=>'Liberia','LBY'=>'Libya','LIE'=>'Liechtenstein',
				'LTU'=>'Lithuania','LUX'=>'Luxembourg','MAC'=>'Macao','MKD'=>'Macedonia, the former Yugoslav Republic of','MDG'=>'Madagascar','MWI'=>'Malawi','MYS'=>'Malaysia','MDV'=>'Maldives','MLI'=>'Mali','MLT'=>'Malta','MHL'=>'Marshall Islands','MTQ'=>'Martinique','MRT'=>'Mauritania','MUS'=>'Mauritius','MYT'=>'Mayotte','MEX'=>'Mexico',
				'FSM'=>'Micronesia, Federated States of','MDA'=>'Moldova, Republic of','MCO'=>'Monaco','MNG'=>'Mongolia','MNE'=>'Montenegro','MSR'=>'Montserrat','MAR'=>'Morocco','MOZ'=>'Mozambique','MMR'=>'Myanmar','NAM'=>'Namibia','NRU'=>'Nauru','NPL'=>'Nepal',
				'NLD'=>'Netherlands','NCL'=>'New Caledonia','NZL'=>'New Zealand','NIC'=>'Nicaragua','NER'=>'Niger','NGA'=>'Nigeria','NIU'=>'Niue','NFK'=>'Norfolk Island','MNP'=>'Northern Mariana Islands','NOR'=>'Norway','OMN'=>'Oman','PAK'=>'Pakistan','PLW'=>'Palau','PSE'=>'Palestinian Territory, Occupied','PAN'=>'Panama','PNG'=>'Papua New Guinea',
				'PRY'=>'Paraguay','PER'=>'Peru','PHL'=>'Philippines','PCN'=>'Pitcairn','POL'=>'Poland','PRT'=>'Portugal','PRI'=>'Puerto Rico','QAT'=>'Qatar','REU'=>'Reunion','ROU'=>'Romania','RUS'=>'Russian Federation','RWA'=>'Rwanda','BLM'=>'Saint Barthelemy','SHN'=>'Saint Helena, Ascension and Tristan da Cunha','KNA'=>'Saint Kitts and Nevis','LCA'=>'Saint Lucia',
				'MAF'=>'Saint Martin (French part)','SPM'=>'Saint Pierre and Miquelon','VCT'=>'Saint Vincent and the Grenadines','WSM'=>'Samoa','SMR'=>'San Marino','STP'=>'Sao Tome and Principe','SAU'=>'Saudi Arabia','SEN'=>'Senegal','SRB'=>'Serbia','SYC'=>'Seychelles','SLE'=>'Sierra Leone','SGP'=>'Singapore',
				'SXM'=>'Sint Maarten (Dutch part)','SVK'=>'Slovakia','SVN'=>'Slovenia','SLB'=>'Solomon Islands','SOM'=>'Somalia','ZAF'=>'South Africa','SGS'=>'South Georgia and the South Sandwich Islands','SSD'=>'South Sudan','ESP'=>'Spain','LKA'=>'Sri Lanka','SDN'=>'Sudan','SUR'=>'Suriname',	'SJM'=>'Svalbard and Jan Mayen','SWZ'=>'Swaziland','SWE'=>'Sweden','CHE'=>'Switzerland',
				'SYR'=>'Syrian Arab Republic','TWN'=>'Taiwan, Province of China','TJK'=>'Tajikistan','TZA'=>'Tanzania, United Republic of','THA'=>'Thailand','TLS'=>'Timor-Leste','TGO'=>'Togo','TKL'=>'Tokelau','TON'=>'Tonga','TTO'=>'Trinidad and Tobago','TUN'=>'Tunisia','TUR'=>'Turkey',
				'TKM'=>'Turkmenistan','TCA'=>'Turks and Caicos Islands','TUV'=>'Tuvalu','UGA'=>'Uganda','UKR'=>'Ukraine','ARE'=>'United Arab Emirates','GBR'=>'United Kingdom','USA'=>'United States','UMI'=>'United States Minor Outlying Islands','URY'=>'Uruguay','UZB'=>'Uzbekistan','VUT'=>'Vanuatu','VEN'=>'Venezuela, Bolivarian Republic of','VNM'=>'Viet Nam','VGB'=>'Virgin Islands, British',
				'VIR'=>'Virgin Islands, U.S.','WLF'=>'Wallis and Futuna','ESH'=>'Western Sahara','YEM'=>'Yemen','ZMB'=>'Zambia','ZWE'=>'Zimbabwe'
		);
			
		return $country;
	
	
	}
		function getCountry_sendMoney()
	{
		$country = array('AFG'=>'Afghanistan','ALA'=>'Aland Islands','ALB'=>'Albania','DZA'=>'Algeria','ASM'=>'American Samoa','AND'=>'Andorra','AGO'=>'Angola','AIA'=>'Anguilla','ATA'=>'Antarctica','ATG'=>'Antigua and Barbuda','ARG'=>'Argentina','ARM'=>'Armenia','ABW'=>'Aruba','AUS'=>'Australia','AUT'=>'Austria','AZE'=>'Azerbaijan',
				'BHS'=>'Bahamas','BHR'=>'Bahrain','BGD'=>'Bangladesh','BRB'=>'Barbados','BLR'=>'Belarus','BEL'=>'Belgium','BLZ'=>'Belize','BEN'=>'Benin','BMU'=>'Bermuda','BTN'=>'Bhutan','BOL'=>'Bolivia, Plurinational State of','BES'=>'Bonaire, Sint Eustatius and Saba','BIH'=>'Bosnia and Herzegovina','BWA'=>'Botswana','BVT'=>'Bouvet Island','BRA'=>'Brazil',
				'IOT'=>'British Indian Ocean Territory','BRN'=>'Brunei Darussalam','BGR'=>'Bulgaria','BFA'=>'Burkina Faso',	'BDI'=>'Burundi','KHM'=>'Cambodia',	'CMR'=>'Cameroon','CAN'=>'Canada','CPV'=>'Cape Verde','CYM'=>'Cayman Islands','CAF'=>'Central African Republic','TCD'=>'Chad','CHL'=>'Chile','CHN'=>'China','CXR'=>'Christmas Island','CCK'=>'Cocos (Keeling) Islands',
				'COL'=>'Colombia','COM'=>'Comoros','COG'=>'Congo','COD'=>'Congo, the Democratic Republic of the','COK'=>'Cook Islands','CRI'=>'Costa Rica','CIV'=>"Cote d'Ivoire",'HRV'=>'Croatia','CUB'=>'Cuba','CUW'=>'Curacao','CYP'=>'Cyprus','CZE'=>'Czech Republic','DNK'=>'Denmark','DJI'=>'Djibouti','DMA'=>'Dominica','DOM'=>'Dominican Republic',
				'ECU'=>'Ecuador','EGY'=>'Egypt','SLV'=>'El Salvador','GNQ'=>'Equatorial Guinea','ERI'=>'Eritrea','EST'=>'Estonia','ETH'=>'Ethiopia','FLK'=>'Falkland Islands (Malvinas)','FRO'=>'Faroe Islands','FJI'=>'Fiji','FIN'=>'Finland','FRA'=>'France','GUF'=>'French Guiana','PYF'=>'French Polynesia','ATF'=>'French Southern Territories','GAB'=>'Gabon',
				'GMB'=>'Gambia','GEO'=>'Georgia','DEU'=>'Germany','GHA'=>'Ghana','GIB'=>'Gibraltar','GRC'=>'Greece','GRL'=>'Greenland','GRD'=>'Grenada','GLP'=>'Guadeloupe','GUM'=>'Guam','GTM'=>'Guatemala','GGY'=>'Guernsey','GIN'=>'Guinea','GNB'=>'Guinea-Bissau','GUY'=>'Guyana','HTI'=>'Haiti',
				'HMD'=>'Heard Island and McDonald Islands','VAT'=>'Holy See (Vatican City State)','HND'=>'Honduras','HKG'=>'Hong Kong','HUN'=>'Hungary','ISL'=>'Iceland','IND'=>'India','IDN'=>'Indonesia','IRN'=>'Iran, Islamic Republic of','IRQ'=>'Iraq','IRL'=>'Ireland','IMN'=>'Isle of Man','ISR'=>'Israel','ITA'=>'Italy',	'JAM'=>'Jamaica','JPN'=>'Japan',
				'JEY'=>'Jersey','JOR'=>'Jordan','KAZ'=>'Kazakhstan','KEN'=>'Kenya','KIR'=>'Kiribati','PRK'=>"Korea, Democratic People's Republic of",'KOR'=>'Korea, Republic of','KWT'=>'Kuwait','KGZ'=>'Kyrgyzstan','LAO'=>"Lao People's Democratic Republic",'LVA'=>'Latvia','LBN'=>'Lebanon','LSO'=>'Lesotho','LBR'=>'Liberia','LBY'=>'Libya','LIE'=>'Liechtenstein',
				'LTU'=>'Lithuania','LUX'=>'Luxembourg','MAC'=>'Macao','MKD'=>'Macedonia, the former Yugoslav Republic of','MDG'=>'Madagascar','MWI'=>'Malawi','MYS'=>'Malaysia','MDV'=>'Maldives','MLI'=>'Mali','MLT'=>'Malta','MHL'=>'Marshall Islands','MTQ'=>'Martinique','MRT'=>'Mauritania','MUS'=>'Mauritius','MYT'=>'Mayotte','MEX'=>'Mexico',
				'FSM'=>'Micronesia, Federated States of','MDA'=>'Moldova, Republic of','MCO'=>'Monaco','MNG'=>'Mongolia','MNE'=>'Montenegro','MSR'=>'Montserrat','MAR'=>'Morocco','MOZ'=>'Mozambique','MMR'=>'Myanmar','NAM'=>'Namibia','NRU'=>'Nauru','NPL'=>'Nepal',
				'NLD'=>'Netherlands','NCL'=>'New Caledonia','NZL'=>'New Zealand','NIC'=>'Nicaragua','NER'=>'Niger','NGA'=>'Nigeria','NIU'=>'Niue','NFK'=>'Norfolk Island','MNP'=>'Northern Mariana Islands','NOR'=>'Norway','OMN'=>'Oman','PAK'=>'Pakistan','PLW'=>'Palau','PSE'=>'Palestinian Territory, Occupied','PAN'=>'Panama','PNG'=>'Papua New Guinea',
				'PRY'=>'Paraguay','PER'=>'Peru','PHL'=>'Philippines','PCN'=>'Pitcairn','POL'=>'Poland','PRT'=>'Portugal','PRI'=>'Puerto Rico','QAT'=>'Qatar','REU'=>'Reunion','ROU'=>'Romania','RUS'=>'Russian Federation','RWA'=>'Rwanda','BLM'=>'Saint Barthelemy','SHN'=>'Saint Helena, Ascension and Tristan da Cunha','KNA'=>'Saint Kitts and Nevis','LCA'=>'Saint Lucia',
				'MAF'=>'Saint Martin (French part)','SPM'=>'Saint Pierre and Miquelon','VCT'=>'Saint Vincent and the Grenadines','WSM'=>'Samoa','SMR'=>'San Marino','STP'=>'Sao Tome and Principe','SAU'=>'Saudi Arabia','SEN'=>'Senegal','SRB'=>'Serbia','SYC'=>'Seychelles','SLE'=>'Sierra Leone','SGP'=>'Singapore',
				'SXM'=>'Sint Maarten (Dutch part)','SVK'=>'Slovakia','SVN'=>'Slovenia','SLB'=>'Solomon Islands','SOM'=>'Somalia','ZAF'=>'South Africa','SGS'=>'South Georgia and the South Sandwich Islands','SSD'=>'South Sudan','ESP'=>'Spain','LKA'=>'Sri Lanka','SDN'=>'Sudan','SUR'=>'Suriname',	'SJM'=>'Svalbard and Jan Mayen','SWZ'=>'Swaziland','SWE'=>'Sweden','CHE'=>'Switzerland',
				'SYR'=>'Syrian Arab Republic','TWN'=>'Taiwan, Province of China','TJK'=>'Tajikistan','TZA'=>'Tanzania, United Republic of','THA'=>'Thailand','TLS'=>'Timor-Leste','TGO'=>'Togo','TKL'=>'Tokelau','TON'=>'Tonga','TTO'=>'Trinidad and Tobago','TUN'=>'Tunisia','TUR'=>'Turkey',
				'TKM'=>'Turkmenistan','TCA'=>'Turks and Caicos Islands','TUV'=>'Tuvalu','UGA'=>'Uganda','UKR'=>'Ukraine','ARE'=>'United Arab Emirates'
		);
			
		return $country;
	
	
	}
	
	public static function getTypeOptions($id = null)
	{
		$list = array("TYPE1","TYPE2","TYPE3");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}
	public static function getGenderOptions($id = null)
	{
		$list = array("Male","Female","Other");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}
 	public function beforeValidate()
	{
		if($this->isNewRecord)
		{
					if ( !isset( $this->create_user_id )) $this->create_user_id = Yii::app()->user->id;			
		if ( !isset( $this->create_time )) $this->create_time = new CDbExpression('NOW()');
		}else{
						}
		return parent::beforeValidate();
	}

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{user}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'User|Users', $n);
	}

	public static function representingColumn() {
		return 'full_name';
	}

	public function rules() {
		return array(
			array('first_name,last_name,email,password,gender,birth_date,birth_month,birth_year,birth_country,nationality,mobile,contact_address,city,zipcode,country,emirates_id,emirates_expiry,emirates_front,emirates_back,tos', 'required'),
			array('gender, zipcode, tos,mobile, news_letters, role_id, state_id, type_id, login_error_count, create_user_id', 'numerical', 'integerOnly'=>true),
			array('full_name', 'length', 'max'=>256),
			array('email', 'unique'),
			array('email', 'email'),
			array('email, first_name, last_name, status_msg, city', 'length', 'max'=>128),
			array('mobile', 'length', 'max'=>12),
			array('password, activation_key', 'length', 'max'=>512),
			array('country, nationality', 'length', 'max'=>64),
		//	array('emirates_front,emirates_back', 'file', 'types'=>'jpg, gif, png'),
			array('emirates_id', 'length', 'max'=>54),
			array('date_of_birth,birth_date,birth_month,birth_year,birth_country,contact_address, emirates_expiry, last_visit_time, last_action_time, last_password_change,create_time,birth_date', 'safe'),
			array('mobile, first_name, last_name, status_msg, date_of_birth, gender, contact_address, city, country, nationality, zipcode, emirates_front, emirates_back, emirates_id, emirates_expiry, tos, news_letters, role_id, state_id, type_id, last_visit_time, last_action_time, last_password_change, activation_key, login_error_count, create_user_id, create_time', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, full_name, email, mobile, password, first_name, last_name, status_msg, date_of_birth, gender, contact_address, city, country, nationality, zipcode, emirates_front, emirates_back, emirates_id, emirates_expiry, tos, news_letters, role_id, state_id, type_id, last_visit_time, last_action_time, last_password_change, activation_key, login_error_count, create_user_id, create_time', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'full_name' => Yii::t('app', 'Full Name'),
			'email' => Yii::t('app', 'Email'),
			'mobile' => Yii::t('app', 'Mobile No.'),
			'password' => Yii::t('app', 'Password'),
			'password_2' => Yii::t('app', 'Confirm Password'),
			'first_name' => Yii::t('app', 'First Name'),
			'last_name' => Yii::t('app', 'Last Name'),
			'status_msg' => Yii::t('app', 'Status Msg'),
			'date_of_birth' => Yii::t('app', 'Date Of Birth'),
			'birth_date' => Yii::t('app', 'Date Of Birth'),
			'birth_month' => Yii::t('app', 'Month Of Birth'),
			'birth_year' => Yii::t('app', 'Year Of Birth'),
			'gender' => Yii::t('app', 'Gender'),
			'contact_address' => Yii::t('app', 'Address'),
			'city' => Yii::t('app', 'City'),
			'country' => Yii::t('app', 'Country'),
				'birth_country' => Yii::t('app', 'Country of birth'),
			'nationality' => Yii::t('app', 'Nationality'),
			'zipcode' => Yii::t('app', 'Post Code'),
			'emirates_front' => Yii::t('app', 'ID Proof'),
			'emirates_back' => Yii::t('app', 'Address Proof'),
			'emirates_id' => Yii::t('app', 'Emirates Id number'),
			'emirates_expiry' => Yii::t('app', 'Expiry date of emirates id'),
			'tos' => Yii::t('app', 'I accept your '.CHtml::link('terms and conditions',array(''))),
			'news_letters' => Yii::t('app', 'News Letters'),
			'role_id' => Yii::t('app', 'Role'),
			'state_id' => Yii::t('app', 'State'),
			'type_id' => Yii::t('app', 'Type'),
			'last_visit_time' => Yii::t('app', 'Last Visit Time'),
			'last_action_time' => Yii::t('app', 'Last Action Time'),
			'last_password_change' => Yii::t('app', 'Last Password Change'),
			'activation_key' => Yii::t('app', 'Activation Key'),
			'login_error_count' => Yii::t('app', 'Login Error Count'),
			'create_user_id' => Yii::t('app', 'Create User'),
			'create_time' => Yii::t('app', 'Create Time'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('full_name', $this->full_name, true);
		$criteria->compare('email', $this->email, true);
		$criteria->compare('mobile', $this->mobile, true);
		$criteria->compare('password', $this->password, true);
		$criteria->compare('first_name', $this->first_name, true);
		$criteria->compare('last_name', $this->last_name, true);
		$criteria->compare('status_msg', $this->status_msg, true);
		$criteria->compare('date_of_birth', $this->date_of_birth, true);
		$criteria->compare('birth_date', $this->birth_date, true);
		$criteria->compare('birth_month', $this->birth_month, true);
		$criteria->compare('birth_year', $this->birth_year, true);
		$criteria->compare('gender', $this->gender);
		$criteria->compare('contact_address', $this->contact_address, true);
		$criteria->compare('city', $this->city, true);
		$criteria->compare('country', $this->country, true);
		$criteria->compare('birth_country', $this->birth_country, true);
		$criteria->compare('nationality', $this->nationality, true);
		$criteria->compare('zipcode', $this->zipcode);
		$criteria->compare('emirates_front', $this->emirates_front, true);
		$criteria->compare('emirates_back', $this->emirates_back, true);
		$criteria->compare('emirates_id', $this->emirates_id, true);
		$criteria->compare('emirates_expiry', $this->emirates_expiry, true);
		$criteria->compare('tos', $this->tos);
		$criteria->compare('news_letters', $this->news_letters);
		$criteria->compare('role_id', $this->role_id);
		$criteria->compare('state_id', $this->state_id);
		$criteria->compare('type_id', $this->type_id);
		$criteria->compare('last_visit_time', $this->last_visit_time, true);
		$criteria->compare('last_action_time', $this->last_action_time, true);
		$criteria->compare('last_password_change', $this->last_password_change, true);
		$criteria->compare('activation_key', $this->activation_key, true);
		$criteria->compare('login_error_count', $this->login_error_count);
		$criteria->compare('create_user_id', $this->create_user_id);
		$criteria->compare('create_time', $this->create_time, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}