<?php

/**
 * Company: Yee Technologies Pvt. Ltd. < www.yeetechnologies.com >
 * Author : Praveen Shivhare < praveen.tuffgeekers@gmail.com >
 */
 
/**
 * This is the model base class for the table "{{transaction_log}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TransactionLog".
 *
 * Columns in table "{{transaction_log}}" available as properties of the model,
 * followed by relations of table "{{transaction_log}}" available as properties of the model.
 *
 * @property integer $id
 * @property string $transaction_id
 * @property integer $transaction_status_id
 * @property string $date_created
 * @property string $date_modified
 * @property integer $created_by
 * @property integer $updated_by
 * @property string $notes
 * @property string $browser
 * @property string $platform
 * @property string $version
 *
 * @property Lookup $transactionStatus
 * @property Transaction $transaction
 */
abstract class BaseTransactionLog extends GxActiveRecord {


	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{transaction_log}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'TransactionLog|TransactionLogs', $n);
	}

	public static function representingColumn() {
		return 'date_created';
	}

	public function rules() {
		return array(
			array('transaction_id, transaction_status_id, date_created, date_modified, created_by, updated_by', 'required'),
			array('transaction_status_id, created_by, updated_by', 'numerical', 'integerOnly'=>true),
			array('transaction_id, platform, version', 'length', 'max'=>45),
			array('notes, browser', 'safe'),
			array('notes, browser, platform, version', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, transaction_id, transaction_status_id, date_created, date_modified, created_by, updated_by, notes, browser, platform, version', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'transactionStatus' => array(self::BELONGS_TO, 'Lookup', 'transaction_status_id'),
			'transaction' => array(self::BELONGS_TO, 'Transaction', 'transaction_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'transaction_id' => null,
			'transaction_status_id' => null,
			'date_created' => Yii::t('app', 'Date Created'),
			'date_modified' => Yii::t('app', 'Date Modified'),
			'created_by' => Yii::t('app', 'Created By'),
			'updated_by' => Yii::t('app', 'Updated By'),
			'notes' => Yii::t('app', 'Notes'),
			'browser' => Yii::t('app', 'Browser'),
			'platform' => Yii::t('app', 'Platform'),
			'version' => Yii::t('app', 'Version'),
			'transactionStatus' => null,
			'transaction' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('transaction_id', $this->transaction_id);
		$criteria->compare('transaction_status_id', $this->transaction_status_id);
		$criteria->compare('date_created', $this->date_created, true);
		$criteria->compare('date_modified', $this->date_modified, true);
		$criteria->compare('created_by', $this->created_by);
		$criteria->compare('updated_by', $this->updated_by);
		$criteria->compare('notes', $this->notes, true);
		$criteria->compare('browser', $this->browser, true);
		$criteria->compare('platform', $this->platform, true);
		$criteria->compare('version', $this->version, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}